select * from policy
select * from Policy_Benefits
select * from Policy_Application
select * from Policyholder
select * from Policyholder_phone
select * from Beneficiary
select * from Benefeciary_phone
select * from Claim
select * from Employee
select * from Inquiry
select * from Payment
select * from Processes_emp_claim
select * from Processes_emp_inquiry
select * from Processes_emp_polApp